#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: root
    password: Holydude93!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

clientId: 474339377424-mufjbd5juv939iukdqpa09m15uudmd3b.apps.googleusercontent.com